-- ==============================================================================
-- NoteVerse Database Upgrade V2 (Non-Destructive)
-- ==============================================================================
-- This script upgrades your existing Supabase database to the new "Modern Platform" 
-- architecture without deleting your current user data or notes.
--
-- Features Added:
-- 1. RBAC (Roles & Permissions)
-- 2. LMS Capabilities (Courses, Enrollments)
-- 3. AI Readiness (Vector fields on Profiles)
-- 4. Audit Logging

BEGIN;

-- ------------------------------------------------------------------------------
-- 1. Upgrade User Profiles for AI & Compliance
-- ------------------------------------------------------------------------------
-- We extend the existing 'profiles' table instead of replacing it, 
-- to keep your React app working perfectly.

ALTER TABLE public.profiles 
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS learning_style_vector JSONB DEFAULT '{}'::jsonb, -- AI Ready
    ADD COLUMN IF NOT EXISTS weak_subject_areas TEXT[],
    ADD COLUMN IF NOT EXISTS failed_login_attempts INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

-- ------------------------------------------------------------------------------
-- 2. Implement Role-Based Access Control (RBAC)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    permissions JSONB DEFAULT '{}'::jsonb
);

INSERT INTO public.roles (name, permissions) VALUES
    ('admin', '{"all": true}'),
    ('teacher', '{"create_course": true, "grade": true}'),
    ('student', '{"enroll": true}'),
    ('parent', '{"view_progress": true}')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE, -- Linking to profiles/users
    role_id INT REFERENCES public.roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, role_id)
);

-- Auto-assign 'student' role to all existing users for backward compatibility
INSERT INTO public.user_roles (user_id, role_id)
SELECT id, (SELECT id FROM public.roles WHERE name = 'student')
FROM public.profiles
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------------------------
-- 3. Add Course Management (LMS)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.courses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    teacher_id UUID REFERENCES public.profiles(id), -- The Creator
    difficulty_level VARCHAR(50) DEFAULT 'Beginner',
    metadata JSONB DEFAULT '{}'::jsonb, -- AI Tags
    is_published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.enrollments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id),
    course_id UUID REFERENCES public.courses(id),
    status VARCHAR(20) DEFAULT 'active',
    enrolled_at TIMESTAMPTZ DEFAULT NOW(),
    final_grade DECIMAL(5, 2),
    UNIQUE(student_id, course_id)
);

-- ------------------------------------------------------------------------------
-- 4. Deep Analytics & Logs
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action_type VARCHAR(50) NOT NULL, 
    entity_type VARCHAR(50), 
    entity_id UUID,
    changes JSONB, -- What changed
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 5. Security Policies (RLS)
-- ------------------------------------------------------------------------------

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Simple policies to get started
CREATE POLICY "Public read courses" ON public.courses FOR SELECT USING (is_published = TRUE);
CREATE POLICY "Teachers manage courses" ON public.courses FOR ALL USING (auth.uid() = teacher_id);
CREATE POLICY "Students see own enrollments" ON public.enrollments FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Users insert logs" ON public.activity_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ------------------------------------------------------------------------------
COMMIT;

NOTIFY pgrst, 'reload schema';
